channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch_lightning
  - torch
  - transformers
  - custom_losses
  - pandas
  - torch
  - dataset
  - datasets
  - dataLoader
  - pandas
  - AutoTokenizer
  - numpy
  - time
  - unittest
  - python
  - pycodestyle
  - data_utils
  - os
  - logging
  - argparse
  - backbone_tuners
  - nltk
  - boto3
  - embedding_backbone
