channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch_lightning
  - torch
  - transformers
  - CosineEmbeddingLoss
  - cosine_similarity
  - pandas
  - torch
  - torch.nn.functional
  - Dataset
  - DataLoader
  - pandas
  - AutoTokenizer
  - numpy
  - time
  - unittest
  - python
  - pycodestyle
